# Generated by Django 4.2.2 on 2023-10-18 15:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("servicios_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="servicio",
            options={"verbose_name": "servicio", "verbose_name_plural": "servicios"},
        ),
    ]
