# Generated by Django 4.2.2 on 2023-10-18 15:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"verbose_name": "post", "verbose_name_plural": "posts"},
        ),
    ]
