# Generated by Django 4.2.2 on 2023-11-07 15:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog_app", "0002_alter_post_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="categorias",
            field=models.ManyToManyField(
                related_name="mi_nombre_atributo", to="blog_app.categoria"
            ),
        ),
    ]
